version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 5
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  backend:
    build:
        context: ./docker/backend
        dockerfile: Dockerfile
    volumes:
      - .:/app

volumes:
    database_data: